version: "3.9"
services:
  crypto-backend:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    restart: always
    volumes:
      - ./crypto_data:/app/crypto_data
      - ./predictions:/app/predictions

